title = "cjson"
version = "1.7.18"
description = "cJSON is an ultra-lightweight JSON parser and writer for C. It is designed to be minimal, fast, and easy to integrate into any C project. It is one of the most popular JSON libraries for C."
license = "MIT"
dependencies = "None (pure C library)"
recipe_url = "https://github.com/DaveGamble/cJSON.git"
