title = "pulseaudio"
version = "17.0"
description = "PulseAudio is a sound server providing advanced features including per-application volume control, switching between audio devices, and network audio. It is the default sound server for most Linux desktop environments."
license = "LGPL-2.1"
dependencies = "glib"
recipe_url = "https://freedesktop.org/software/pulseaudio/releases/pulseaudio-17.0.tar.xz"
