title = "libevent"
version = "2.1.13"
description = "libevent is an event notification library for developing scalable network servers. It provides a mechanism to execute a callback function when a specific event occurs on a file descriptor or after a timeout."
license = "MIT"
dependencies = "openssl (optional)"
recipe_url = "https://github.com/libevent/libevent/releases/download/release-2.1.13/libevent-2.1.13.tar.gz"
