title = "dbus"
version = "1.16.0"
description = "D-Bus is a message bus system for inter-process communication in Linux desktop environments. It provides a simple way for applications to communicate with each other and the system, used by systemd, GNOME, and KDE."
license = "GPL-2.0"
dependencies = "expat"
recipe_url = "https://dbus.freedesktop.org/releases/dbus/dbus-1.16.0.tar.gz"
