title = "pcre"
version = "8.45"
description = "PCRE (Perl Compatible Regular Expressions) is a library implementing regular expression pattern matching. It provides functionality similar to Perl's regex engine and is used by many applications including grep, Apache, and PHP."
license = "BSD"
dependencies = "None (self-contained)"
canonical_name = "pcre"
recipe_url = "https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.gz"
