title = "cunit"
version = "2.1-3"
description = "CUnit is a lightweight unit testing framework for C. It provides a simple API for writing test cases, test suites, and test runners, inspired by JUnit and other unit testing frameworks."
license = "GPL-2.0"
dependencies = "None (minimal dependencies)"
recipe_url = "https://sourceforge.net/projects/cunit/files/CUnit/2.1-3/CUnit-2.1-3.tar.bz2"
