title = "mesa"
version = "24.3.4"
description = "Mesa is an open-source implementation of the OpenGL, Vulkan, and other graphics APIs. It provides the graphics driver stack for open-source GPU drivers on Linux and is used by most desktop Linux distributions."
license = "MIT"
dependencies = "llvm"
canonical_name = "mesa"
recipe_url = "https://archive.mesa3d.org/mesa-24.3.4.tar.xz"
