title = "ffmpeg"
version = "7.1.1"
description = "FFmpeg is the leading multimedia framework for encoding, decoding, transcoding, muxing, demuxing, streaming, and playing virtually all formats. It includes libavcodec, libavutil, libavformat, libavfilter, and other libraries."
license = "GPL-3.0"
dependencies = "libx264"
canonical_name = "ffmpeg"
recipe_url = "https://ffmpeg.org/releases/ffmpeg-7.1.1.tar.xz"
