title = "curl"
version = "8.11.1"
description = "libcurl is a free, easy-to-use URL transfer library supporting HTTP, HTTPS, FTP, FTPS, SCP, SFTP, TFTP, DICT, TELNET, LDAP, POP3, IMAP, SMTP, RTSP, RTMP, and many other protocols. It is the most widely used C HTTP client library."
license = "curl"
dependencies = "openssl (or wolfssl, mbedtls)"
canonical_name = "curl"
recipe_url = "https://curl.se/download/curl-8.11.1.tar.gz"
