title = "hello-world"
version = "1.0"
description = "A trivial hello world C library for testing purposes"
license = "MIT"
dependencies = "None"
canonical_name = "coffee-hello-world"
recipe_url = "https://github.com/coffee-clang/hello-world/archive/refs/tags/1.0.tar.gz"
