title = "tiff"
version = "4.7.0"
description = "LibTIFF provides support for the Tag Image File Format (TIFF), a widely used format for high-quality image storage. It provides functions for reading, writing, and manipulating TIFF images."
license = "MIT"
dependencies = "libjpeg"
canonical_name = "tiff"
recipe_url = "https://download.osgeo.org/libtiff/tiff-4.7.0.tar.gz"
