title = "libexif"
version = "0.6.24"
description = "libexif is a library for parsing, editing, and saving EXIF metadata from digital camera images. It supports reading and writing EXIF tags from JPEG, TIFF, and PNG files."
license = "LGPL-2.1"
dependencies = "libjpeg"
canonical_name = "exif"
recipe_url = "https://github.com/libexif/libexif/releases/download/v0.6.24/libexif-0.6.24.tar.gz"
