title = "freetype"
version = "2.13.3"
description = "FreeType is a freely available software library for rendering fonts. It provides a uniform interface to access font content and is used by most Linux desktop environments, browsers, and ebook readers."
license = "FreeType"
dependencies = "zlib (optional, for bitmap fonts)"
canonical_name = "freetype"
recipe_url = "https://download.savannah.nongnu.org/releases/freetype/freetype-2.13.3.tar.gz"
